# Generated by Django 4.0.3 on 2022-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='age',
            field=models.CharField(default=22, max_length=10),
        ),
        migrations.AddField(
            model_name='mydata',
            name='email',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='mydata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mydata',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mydata',
            name='specialty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mydata',
            name='website',
            field=models.CharField(default='', max_length=40),
        ),
    ]
