# Generated by Django 4.0.3 on 2022-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_mydata_age_mydata_email_mydata_name_mydata_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='address',
            field=models.CharField(default='', max_length=45),
        ),
    ]
