# Generated by Django 4.0.3 on 2022-03-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_mydata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='degree',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mydata',
            name='freelance',
            field=models.BooleanField(default=True, max_length=20),
        ),
    ]
