# Generated by Django 4.0.3 on 2022-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_mydata_degree_mydata_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
